from typing import Protocol
from app.domain.entities.dataset import Dataset
from app.domain.entities.analysis_result import AnalysisResult


class DatasetRepository(Protocol):
    def save(self, dataset: Dataset) -> Dataset: ...
    def get_by_id(self, dataset_id: str) -> Dataset | None: ...
    def list_all(self) -> list[Dataset]: ...


class AnalysisResultRepository(Protocol):
    def save(self, result: AnalysisResult) -> AnalysisResult: ...
    def get_by_id(self, result_id: str) -> AnalysisResult | None: ...
    def list_by_dataset(self, dataset_id: str) -> list[AnalysisResult]: ...
