from typing import Protocol


class FileStorage(Protocol):
    def save(self, filename: str, content: bytes) -> str: ...
    def save(self, filename: str, content: bytes, user_id: str = "") -> str: ...
    def get_path(self, stored_path: str) -> str: ...
