from typing import BinaryIO, Protocol


class FileStorage(Protocol):
    def save(self, filename: str, content: bytes, user_id: str = "") -> str: ...

    def save_stream(self, filename: str, stream: BinaryIO, user_id: str = "") -> str: ...

    def get_path(self, stored_path: str) -> str: ...
